apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flask-meeting-minutes-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-meeting-minutes
  minReplicas: 1
  maxReplicas: 40
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
