apiVersion: v1
kind: Service
metadata:
  name: meeting-ninjaAi-service
spec:
  type: NodePort
  selector:
    app: meeting-ninjaAi-api
  ports:
    - protocol: TCP
      port: 32000
      targetPort: 32000
      nodePort: 32000
