apiVersion: v1
kind: Service
metadata:
  name: meeting-ninja-service
spec:
  type: NodePort
  selector:
    app: meeting-ninja-api
  ports:
    - protocol: TCP
      port: 32200
      targetPort: 32200
      nodePort: 32200
